# Generated by Django 6.0.5 on 2026-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_avaliacao_aluno_avaliacao_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.CharField(choices=[('monte_castelo', 'São Luís - Monte Castelo')], default='monte_castelo', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('sistemas_informacao', 'Sistemas de Informação'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_eletrica_industrial', 'Engenharia Elétrica Industrial'), ('engenharia_mecanica_industrial', 'Engenharia Mecânica Industrial'), ('biologia', 'Biologia'), ('fisica', 'Física'), ('matematica', 'Matemática'), ('quimica', 'Química')], default='sistemas_informacao', max_length=50),
        ),
    ]
