# Generated by Django 6.0.5 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='avaliacao_media',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('sistemas_informacao', 'Sistemas de Informação'), ('ads', 'Tecnologia em Análise e Desenvolvimento de Sistemas'), ('informatica', 'Informática'), ('edificacoes', 'Edificações'), ('eletrotecnica', 'Eletrotécnica'), ('administracao', 'Administração'), ('quimica', 'Química'), ('mecanica', 'Mecânica'), ('eletronica', 'Eletrônica'), ('seguranca_trabalho', 'Segurança do Trabalho')], default='sistemas_informacao', max_length=50),
        ),
    ]
