# Generated by Django 6.0.5 on 2026-05-26 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Matrícula inválida')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('curso', models.CharField(choices=[('ads', 'Tecnologia em ADS'), ('internet', 'Informática para Internet'), ('edificacoes', 'Edificações'), ('eletrotecnica', 'Eletrotécnica'), ('administracao', 'Administração'), ('logistica', 'Logística'), ('quimica', 'Química'), ('agroindustria', 'Agroindústria'), ('outro', 'Outro')], default='ads', max_length=50)),
                ('campus', models.CharField(choices=[('monte_castelo', 'São Luís - Monte Castelo'), ('maracana', 'São Luís - Maracanã'), ('imperatriz', 'Imperatriz'), ('caxias', 'Caxias'), ('timon', 'Timon'), ('bacabal', 'Bacabal'), ('codó', 'Codó'), ('açailândia', 'Açailândia'), ('outro', 'Outro')], default='monte_castelo', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('avaliacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('emprestimos_realizados', models.PositiveIntegerField(default=0)),
                ('emprestimos_concluidos', models.PositiveIntegerField(default=0)),
                ('is_ativo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_bloqueado', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('livros', 'Livros'), ('eletronicos', 'Eletrônicos'), ('academicos', 'Materiais Acadêmicos'), ('ferramentas', 'Ferramentas'), ('dinheiro', 'Dinheiro'), ('moveis', 'Móveis'), ('equipamentos', 'Equipamentos'), ('outros', 'Outros')], max_length=30)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('periodo', models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Por dia'), ('semana', 'Por semana'), ('mes', 'Por mês'), ('combinavel', 'Combinável')], default='semana', max_length=20)),
                ('prazo_maximo', models.CharField(default='Combinável', max_length=50)),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='bom', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_itens/')),
                ('disponivel', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_combinado', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_cedidos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='core.item')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('conteudo_inadequado', 'Conteúdo inadequado'), ('golpe', 'Golpe ou fraude'), ('informacao_falsa', 'Informações falsas'), ('item_proibido', 'Item proibido'), ('comportamento', 'Comportamento inadequado'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('usuario_denunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.item')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
