# Generated by Django 6.0.5 on 2026-06-01 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='avaliacao',
            new_name='avaliacao_media',
        ),
        migrations.RemoveField(
            model_name='item',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.CharField(choices=[('monte_castelo', 'São Luís - Monte Castelo'), ('maracana', 'São Luís - Maracanã'), ('imperatriz', 'Imperatriz'), ('caxias', 'Caxias'), ('timon', 'Timon'), ('bacabal', 'Bacabal'), ('codo', 'Codó'), ('acailandia', 'Açailândia'), ('outro', 'Outro')], default='monte_castelo', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.CharField(choices=[('conteudo_inadequado', 'Conteúdo inadequado'), ('informacao_falsa', 'Informações falsas'), ('item_proibido', 'Item proibido'), ('comportamento', 'Comportamento inadequado'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('livros', 'Livros'), ('eletronicos', 'Eletrônicos'), ('academicos', 'Materiais Acadêmicos'), ('ferramentas', 'Ferramentas'), ('moveis', 'Móveis'), ('equipamentos', 'Equipamentos'), ('outros', 'Outros')], max_length=30),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.emprestimo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
