# Generated by Django 6.0.5 on 2026-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_campus_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('engenharia_civil', 'Engenharia Civil'), ('engenharia_eletrica_industrial', 'Engenharia Elétrica Industrial'), ('engenharia_mecanica_industrial', 'Engenharia Mecânica Industrial'), ('sistemas_informacao', 'Sistemas de Informação'), ('design', 'Design'), ('ciencias_biologicas', 'Ciências Biológicas'), ('fisica', 'Física'), ('matematica', 'Matemática'), ('quimica', 'Química'), ('processos_quimicos', 'Processos Químicos')], default='sistemas_informacao', max_length=50),
        ),
    ]
