# Generated by Django 6.0.5 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aluno_avaliacao_media_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('sistemas_informacao', 'Sistemas de Informação'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_eletrica_industrial', 'Engenharia Elétrica Industrial'), ('engenharia_mecanica_industrial', 'Engenharia Mecânica Industrial'), ('biologia', 'Ciências Biológicas'), ('fisica', 'Física'), ('matematica', 'Matemática'), ('quimica', 'Química'), ('design', 'Design'), ('processos_quimicos', 'Processos Químicos')], default='sistemas_informacao', max_length=50),
        ),
    ]
